#ifndef HEATGUARD_CONFIG_H
#define HEATGUARD_CONFIG_H

/* Application behavior. Change these values through review, not in drivers. */
#define HEATGUARD_EVENT_QUEUE_LENGTH 12U
#define HEATGUARD_EVENT_QUEUE_WAIT_MS 20U
#define HEATGUARD_KEY_DEBOUNCE_MS 20U
#define HEATGUARD_KEY_SAMPLE_MS 10U
#define HEATGUARD_KEY_LONG_PRESS_MS 1000U
#define HEATGUARD_SENSOR_PERIOD_MS 1000U

#define HEATGUARD_MAX_COOKING_SECONDS 200U
#define HEATGUARD_COOKING_TIME_STEP_SECONDS 20U
#define HEATGUARD_OVERTEMPERATURE_C 30U
#define HEATGUARD_MAX_SENSOR_ERRORS 3U

#endif
